image: gcc
before_script:
 - export TERM=xterm-256color
 - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
 - export USER=ciGitlab
 - ./create_enviroment.sh 
 - ./setup_ci.sh
 - export USER=ciGitlab
 - g++ --version
 - gcov --version


############ MWOZNIAK BUILDS ############

CI_BUILD:
  only:
    - ciBranch
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh
    - mv /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation/html/index.html /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation/html/1_DOCUMENTATION.html
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation
      expire_in: 1 week

CI_UT:
  only:
    - ciBranch
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/
    - ./messenger_binary_UT
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/
    - lcov --capture --directory .. --output-file coverage.info
    - lcov --remove coverage.info '*Test*' '/usr/include/*' '/usr/lib/*' '*googletest*' -o coverageWithoutUnnecessaryFiles.info
    - genhtml coverageWithoutUnnecessaryFiles.info --output-directory out
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/Logger_default.txt
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/out
      expire_in: 1 week  




############ MASTER BUILDS ############

MASTER_BUILD:
  only:
    - master
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh
    - mv /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation/html/index.html /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation/html/1_DOCUMENTATION.html
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation
      expire_in: 1 week

MASTER_UT:
  only:
    - master
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/
    - ./messenger_binary_UT
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/Logger_default.txt
      expire_in: 1 week  

MASTER_VALGRIND:
  only:
    - master
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/
    - make valgrind
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - bash check_valgrind_job_status.sh ../build/valgrindOutput.txt
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/valgrindOutput.txt
      expire_in: 1 week

MASTER_CLANG_TIDY:
  only:
    - master
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/
    - python ../scripts/run-clang-tidy.py > /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/clangOutput.txt
    #TODO mnurzyns remove # after removing clang-tidy erros
    #- cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    #- bash check_clang-tidy_job_status.sh /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/clangOutput.txt
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/clangOutput.txt
      expire_in: 1 week


