image: gcc
before_script:
 - ./setup_ci.sh

mwozniakBuild:
  only:
    - mwozniak
  script:
    - ./gcc_ci.sh 

mnurzynsBuild:
  only:
    - mnurzyns
  script:
    - ./gcc_ci.sh

masterBuild:
  only:
    - master
  script:
    - ./gcc_ci.sh
