image: gcc:7.3.0
before_script:
 - export TERM=xterm-256color
 - export USER=ciGitlab
 - export CXX=/usr/local/bin/g++
 - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/local_scripts/create_messenger_enviroment.sh 
 - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/ci_scripts/setup_ci_environment.sh

############ MWOZNIAK BUILDS ############
MWOZNIAK_BUILD:
  only:
    - mwozniak
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - mv /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation/html/index.html /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation/html/1_DOCUMENTATION.html
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation
      expire_in: 1 week

MWOZNIAK_UT:
  only:
    - mwozniak
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/
    - ./messenger_binary_UT
    - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/ci_scripts/generate_ut_coverage_raport_ci.sh
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/Logger_default.txt
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/out
      expire_in: 1 week  

MWOZNIAK_VALGRIND:
  only:
    - mwozniak
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/
    - make valgrind
    - bash /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/ci_scripts/check_valgrind_job_status.sh ../build/valgrindOutput.txt
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/valgrindOutput.txt
      expire_in: 1 week

MWOZNIAK_CLANG_TIDY:
  only:
    - mwozniak
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/
    - python ../scripts/local_scripts/run-clang-tidy.py > /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/clangOutput.txt
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - bash /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/ci_scripts/check_clang-tidy_job_status.sh /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/clangOutput.txt
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/clangOutput.txt
      expire_in: 1 week

############ MNURZYNS BUILDS ############
MNURZYNS_BUILD:
  only:
    - mnurzyns
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - mv /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation/html/index.html /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation/html/1_DOCUMENTATION.html
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation
      expire_in: 1 week

MNURZYNS_UT:
  only:
    - mnurzyns
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/
    - ./messenger_binary_UT
    - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/ci_scripts/generate_ut_coverage_raport_ci.sh
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/Logger_default.txt
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/out
      expire_in: 1 week   

MNURZYNS_VALGRIND:
  only:
    - mnurzyns
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/
    - make valgrind
    - bash /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/ci_scripts/check_valgrind_job_status.sh ../build/valgrindOutput.txt
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/valgrindOutput.txt
      expire_in: 1 week

MNURZYNS_CLANG_TIDY:
  only:
    - mnurzyns
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/
    - python ../scripts/local_scripts/run-clang-tidy.py > /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/clangOutput.txt
    - bash /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/ci_scripts/check_clang-tidy_job_status.sh /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/clangOutput.txt
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/clangOutput.txt
      expire_in: 1 week

############ MASTER BUILDS ############
MASTER_BUILD:
  only:
    - master
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - mv /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation/html/index.html /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation/html/1_DOCUMENTATION.html
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation
      expire_in: 1 week

MASTER_UT:
  only:
    - master
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/
    - ./messenger_binary_UT
    - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/ci_scripts/generate_ut_coverage_raport_ci.sh
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/Logger_default.txt
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/out
      expire_in: 1 week  

MASTER_VALGRIND:
  only:
    - master
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/
    - make valgrind
    - bash /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/ci_scripts/check_valgrind_job_status.sh ../build/valgrindOutput.txt
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/valgrindOutput.txt
      expire_in: 1 week

MASTER_CLANG_TIDY:
  only:
    - master
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/
    - python ../scripts/local_scripts/run-clang-tidy.py > /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/clangOutput.txt
    - bash /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/ci_scripts/check_clang-tidy_job_status.sh /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/clangOutput.txt
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/clangOutput.txt
      expire_in: 1 week

