image: gcc:7.3.0
before_script:
 - export USER=ciGitlab
 - export CXX=/usr/local/bin/g++
 - export PROJECT_DIR=/builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux
 - ${PROJECT_DIR}/scripts/local_scripts/create_messenger_enviroment.sh 
 - ${PROJECT_DIR}/scripts/ci_scripts/setup_ci_environment.sh

############ MWOZNIAK BUILDS ############
MWOZNIAK_BUILD:
  only:
    - mwozniak
  script:
    - cd ${PROJECT_DIR}/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - mv ${PROJECT_DIR}/documentation/html/index.html ${PROJECT_DIR}/documentation/html/1_DOCUMENTATION.html
  artifacts:
      when: always
      paths:
      - ${PROJECT_DIR}/documentation
      expire_in: 1 week

MWOZNIAK_UT:
  only:
    - mwozniak
  script:
    - cd ${PROJECT_DIR}/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - cd ${PROJECT_DIR}/build/bin/
    - ./messenger_binary_UT
    - ${PROJECT_DIR}/scripts/ci_scripts/generate_ut_coverage_raport_ci.sh
  artifacts:
      when: always
      paths:
      - ${PROJECT_DIR}/build/bin/Logger_default.txt
      - ${PROJECT_DIR}/out
      expire_in: 1 week  

MWOZNIAK_VALGRIND:
  only:
    - mwozniak
  script:
    - cd ${PROJECT_DIR}/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - cd ${PROJECT_DIR}/build/
    - make valgrind
    - bash ${PROJECT_DIR}/scripts/ci_scripts/check_valgrind_job_status.sh ../build/valgrindOutput.txt
  artifacts:
      when: always
      paths:
      - ${PROJECT_DIR}/build/valgrindOutput.txt
      expire_in: 1 week

MWOZNIAK_CLANG_TIDY:
  only:
    - mwozniak
  script:
    - cd ${PROJECT_DIR}/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - cd ${PROJECT_DIR}/build/
    - python ../scripts/local_scripts/run-clang-tidy.py > ${PROJECT_DIR}/build/clangOutput.txt
    - cd ${PROJECT_DIR}/scripts/
    - bash ${PROJECT_DIR}/scripts/ci_scripts/check_clang-tidy_job_status.sh ${PROJECT_DIR}/build/clangOutput.txt
  artifacts:
      when: always
      paths:
      - ${PROJECT_DIR}/build/clangOutput.txt
      expire_in: 1 week

############ MNURZYNS BUILDS ############
MNURZYNS_BUILD:
  only:
    - mnurzyns
  script:
    - cd ${PROJECT_DIR}/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - mv ${PROJECT_DIR}/documentation/html/index.html ${PROJECT_DIR}/documentation/html/1_DOCUMENTATION.html
  artifacts:
      when: always
      paths:
      - ${PROJECT_DIR}/documentation
      expire_in: 1 week

MNURZYNS_UT:
  only:
    - mnurzyns
  script:
    - cd ${PROJECT_DIR}/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - cd ${PROJECT_DIR}/build/bin/
    - ./messenger_binary_UT
    - ${PROJECT_DIR}/scripts/ci_scripts/generate_ut_coverage_raport_ci.sh
  artifacts:
      when: always
      paths:
      - ${PROJECT_DIR}/build/bin/Logger_default.txt
      - ${PROJECT_DIR}/out
      expire_in: 1 week   

MNURZYNS_VALGRIND:
  only:
    - mnurzyns
  script:
    - cd ${PROJECT_DIR}/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - cd ${PROJECT_DIR}/build/
    - make valgrind
    - bash ${PROJECT_DIR}/scripts/ci_scripts/check_valgrind_job_status.sh ../build/valgrindOutput.txt
  artifacts:
      when: always
      paths:
      - ${PROJECT_DIR}/build/valgrindOutput.txt
      expire_in: 1 week

MNURZYNS_CLANG_TIDY:
  only:
    - mnurzyns
  script:
    - cd ${PROJECT_DIR}/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - cd ${PROJECT_DIR}/build/
    - python ../scripts/local_scripts/run-clang-tidy.py > ${PROJECT_DIR}/build/clangOutput.txt
    - bash ${PROJECT_DIR}/scripts/ci_scripts/check_clang-tidy_job_status.sh ${PROJECT_DIR}/build/clangOutput.txt
  artifacts:
      when: always
      paths:
      - ${PROJECT_DIR}/build/clangOutput.txt
      expire_in: 1 week

############ MASTER BUILDS ############
MASTER_BUILD:
  only:
    - master
  script:
    - cd ${PROJECT_DIR}/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - mv ${PROJECT_DIR}/documentation/html/index.html ${PROJECT_DIR}/documentation/html/1_DOCUMENTATION.html
  artifacts:
      when: always
      paths:
      - ${PROJECT_DIR}/documentation
      expire_in: 1 week

MASTER_UT:
  only:
    - master
  script:
    - cd ${PROJECT_DIR}/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - cd ${PROJECT_DIR}/build/bin/
    - ./messenger_binary_UT
    - ${PROJECT_DIR}/scripts/ci_scripts/generate_ut_coverage_raport_ci.sh
  artifacts:
      when: always
      paths:
      - ${PROJECT_DIR}/build/bin/Logger_default.txt
      - ${PROJECT_DIR}/out
      expire_in: 1 week  

MASTER_VALGRIND:
  only:
    - master
  script:
    - cd ${PROJECT_DIR}/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - cd ${PROJECT_DIR}/build/
    - make valgrind
    - bash ${PROJECT_DIR}/scripts/ci_scripts/check_valgrind_job_status.sh ../build/valgrindOutput.txt
  artifacts:
      when: always
      paths:
      - ${PROJECT_DIR}/build/valgrindOutput.txt
      expire_in: 1 week

MASTER_CLANG_TIDY:
  only:
    - master
  script:
    - cd ${PROJECT_DIR}/scripts/ci_scripts
    - ./compile_messenger_ci.sh
    - cd ${PROJECT_DIR}/build/
    - python ../scripts/local_scripts/run-clang-tidy.py > ${PROJECT_DIR}/build/clangOutput.txt
    - bash ${PROJECT_DIR}/scripts/ci_scripts/check_clang-tidy_job_status.sh ${PROJECT_DIR}/build/clangOutput.txt
  artifacts:
      when: always
      paths:
      - ${PROJECT_DIR}/build/clangOutput.txt
      expire_in: 1 week

