image: gcc
before_script:
 - export TERM=xterm-256color
 - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
 #- ./create_enviroment.sh 
 #- ./setup_ci.sh
 - export LOG=$(git log -1 --pretty=%B)
 #- export LOG=${LOG:0:2}
 - CI_COMMIT_TAG=${LOG:0:2}
 - echo $CI_COMMIT_TAG

############ MWOZNIAK BUILDS ############

ciBranchBuild#1:
  only:
    - ciBranch
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
  when: $PUBLISH_ARTIFACTS==true





























mwozniakUt:
  only:
    - mwozniak
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/
    - ./messenger_binary_UT
  artifacts:
      when: on_failure
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/Logger_default.txt
      expire_in: 1 week  

mwozniakValgrind:
  only:
    - mwozniak
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/
    - make valgrind
  artifacts:
      when: on_failure
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/valgrindOutput.txt
      expire_in: 1 week

############ MNURZYNS BUILDS ############

mnurzynsBuild:
  only:
    - mnurzyns
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh

mnurzynsUt:
  only:
    - mnurzyns
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/
    - ./messenger_binary_UT
  artifacts:
      when: on_failure
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/Logger_default.txt
      expire_in: 1 week  

mnurzynsValgrind:
  only:
    - mnurzyns
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/
    - make valgrind
  artifacts:
      when: on_failure
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/valgrindOutput.txt
      expire_in: 1 week

############ MASTER BUILDS ############

masterBuild:
  only:
    - master
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh

masterUt:
  only:
    - master
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/
    - ./messenger_binary_UT
  artifacts:
      when: on_failure
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/Logger_default.txt
      expire_in: 1 week  

masterValgrind:
  only:
    - master
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/
    - make valgrind
  artifacts:
      when: on_failure
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/valgrindOutput.txt
      expire_in: 1 week


