image: gcc
before_script:
 - export TERM=xterm-256color
 - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
 - whoami
 - ps -u root
 - ./create_enviroment.sh 
 - ./setup_ci.sh


############ MNURZYNS BUILDS ############

CI_BUILD:
  only:
    - ciBranch
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh
    - mv /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation/html/index.html /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation/html/1_DOCUMENTATION.html
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation
      expire_in: 1 week

CI_UT:
  only:
    - ciBranch
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/
    - ./messenger_binary_UT
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/Logger_default.txt
      expire_in: 1 week  

CI_VALGRIND:
  only:
    - ciBranch
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/
    - make valgrind
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/valgrindOutput.txt
      expire_in: 1 week

CI_CLANG_TIDY:
  only:
    - ciBranch
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/
    - python ../scripts/run-clang-tidy.py > /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/ClangOutput.txt
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/ClangOutput.txt
      expire_in: 1 week

############ MASTER BUILDS ############

MASTER_BUILD:
  only:
    - master
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh
    - mv /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation/html/index.html /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation/html/1_DOCUMENTATION.html
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation
      expire_in: 1 week

MASTER_UT:
  only:
    - master
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/
    - ./messenger_binary_UT
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/Logger_default.txt
      expire_in: 1 week  

MASTER_VALGRIND:
  only:
    - master
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/
    - make valgrind
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/valgrindOutput.txt
      expire_in: 1 week

MASTER_CLANG_TIDY:
  only:
    - master
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/
    - python ../scripts/run-clang-tidy.py > /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/ClangOutput.txt
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/ClangOutput.txt
      expire_in: 1 week


