image: gcc
before_script:
 - export TERM=xterm-256color
 - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
 - ./create_enviroment.sh 
 - ./setup_ci.sh
 - export USER=ciGitlab

############ MWOZNIAK BUILDS ############

MWOZNIAK_BUILD:
  only:
    - mwozniak
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh
    - mv /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation/html/index.html /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation/html/1_DOCUMENTATION.html
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation
      expire_in: 1 week

MWOZNIAK_UT:
  only:
    - mwozniak
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/
    - ./messenger_binary_UT
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/Logger_default.txt
      expire_in: 1 week  

MWOZNIAK_VALGRIND:
  only:
    - mwozniak
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/
    - make valgrind
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/valgrindOutput.txt
      expire_in: 1 week

MWOZNIAK_CLANG_TIDY:
  only:
    - mwozniak
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/
    - python ../scripts/run-clang-tidy.py > /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/ClangOutput.txt
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/ClangOutput.txt
      expire_in: 1 week

############ MNURZYNS BUILDS ############

MNURZYNS_BUILD:
  only:
    - mnurzyns
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh
    - mv /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation/html/index.html /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation/html/1_DOCUMENTATION.html
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation
      expire_in: 1 week

MNURZYNS_UT:
  only:
    - mnurzyns
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/
    - ./messenger_binary_UT
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/Logger_default.txt
      expire_in: 1 week  

MNURZYNS_VALGRIND:
  only:
    - mnurzyns
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/
    - make valgrind
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/valgrindOutput.txt
      expire_in: 1 week

MNURZYNS_CLANG_TIDY:
  only:
    - mnurzyns
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/
    - python ../scripts/run-clang-tidy.py > /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/ClangOutput.txt
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/ClangOutput.txt
      expire_in: 1 week

############ MASTER BUILDS ############

MASTER_BUILD:
  only:
    - master
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh
    - mv /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation/html/index.html /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation/html/1_DOCUMENTATION.html
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/documentation
      expire_in: 1 week

MASTER_UT:
  only:
    - master
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/
    - ./messenger_binary_UT
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/bin/Logger_default.txt
      expire_in: 1 week  

MASTER_VALGRIND:
  only:
    - master
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/
    - make valgrind
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/valgrindOutput.txt
      expire_in: 1 week

MASTER_CLANG_TIDY:
  only:
    - master
  script:
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/scripts/
    - ./gcc_ci.sh 
    - cd /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/
    - python ../scripts/run-clang-tidy.py > /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/ClangOutput.txt
  artifacts:
      when: always
      paths:
      - /builds/NMarcin/MessengerOnFileForLinux/MessengerOnFileForLinux/build/ClangOutput.txt
      expire_in: 1 week


